### ISSUE TITLE
Course variant status enum

### ISSUE THREAD

**Issue by nygrenh** [rage/secret-project-331#55]
* enum
  - Draft - "Hidden from everyone except course staff"
  -  Upcoming - "Course is visible in course listings as upcoming but only a special front page is visible. The special front page could be an optional field on a course variant e.g. `marketing_page_for_before_publishing_id REFERENCES pages`"
  - Active
  - Ended

* Support for automatically opening and closing a course variant based on timestamp
  - binary to headless lms that gets run in a cronjob ("src/bin/update_course_variant_statuses.rs")
```toml
[[bin]]
name = "update-course-variant-statuses"
path = "update_course_variant_statuses.rs"
```

Example chronjob: https://github.com/rage/mooc.fi/blob/master/helm/templates/update-course-statuses-cronjob.yml

command: cargo run --bin update-course-variant-statuses

Starting cronjob manually: `kubectl create job --from cronjob/cronjob-name random-unique-name`
